<center>
<img src="https://habrastorage.org/files/fd4/502/43d/fd450243dd604b81b9713213a247aa20.jpg">
    
## [mlcourse.ai](mlcourse.ai) – Open Machine Learning Course 

<center>Author: [Yury Kashnitskiy](http://yorko.github.io) <br>
Translated and edited by [Sergey Isaev](https://www.linkedin.com/in/isvforall/), [Artem Trunov](https://www.linkedin.com/in/datamove/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina/), and [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/) <br>All content is distributed under the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

**In this task you should use Pandas to answer a few questions about the [Adult](https://archive.ics.uci.edu/ml/datasets/Adult) dataset. (You don't have to download the data – it's already here). Choose the answers in the [web-form](https://docs.google.com/forms/d/1uY7MpI2trKx6FLWZte0uVh3ULV4Cm_tDud0VDFGCOKg). This is a demo version of an assignment, so by submitting the form, you'll see a link to the solution .ipynb file.**

# <center> Assignment #1 (demo)
## <center>  Exploratory data analysis with Pandas

Unique values of all features (for more information, please see the links above):
- `age`: continuous.
- `workclass`: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- `fnlwgt`: continuous.
- `education`: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- `education-num`: continuous.
- `marital-status`: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- `occupation`: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- `relationship`: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- `race`: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- `sex`: Female, Male.
- `capital-gain`: continuous.
- `capital-loss`: continuous.
- `hours-per-week`: continuous.
- `native-country`: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- `salary`: >50K,<=50K

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('adult.data', names = ["age", "workclass", "fnlwgt"
                                         , "education", "education-num", "marital-status"
                                         , "occupation", "relationship", "race", "sex"
                                         , "capital-gain", "capital-loss", "hours-per-week"
                                         , "native-country", "salary"], sep = ", ")
data.head()

<ipython-input-4-01615bdc0451>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data = pd.read_csv('adult.data', names = ["age", "workclass", "fnlwgt"

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. How many men and women (*sex* feature) are represented in this dataset?**

In [5]:
len(data[data['sex'] == 'Female'])

10771

In [6]:
len(data[data['sex'] == 'Male'])

21790

**2. What is the average age (*age* feature) of women?**

In [7]:
data3 = data[data['sex'] == 'Female']

data3["age"].mean()

36.85823043357163

**3. What is the percentage of German citizens (*native-country* feature)?**

In [8]:
data3 = (data[data['native-country'] == 'Germany'])
(len(data3)*1.0/len(data)*1.0)* 100

0.42074874850281013

**4-5. What are the mean and standard deviation of age for those who earn more than 50K per year (*salary* feature) and those who earn less than 50K per year? **

In [9]:
data3 = (data[data['salary'] == '>50K'])

data3['age'].mean()

44.24984058155847

In [10]:
data3["age"].std()

10.51902771985177

In [11]:
data4 = (data[data['salary'] == '<=50K'])
data4['age'].mean()

36.78373786407767

In [12]:
data4['age'].std()

14.020088490824813

**6. Is it true that people who earn more than 50K have at least high school education? (*education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* or *Doctorate* feature)**

In [13]:
data5 = data[(data['salary'] == '>50K')
        & ((data['education'] == 'Bachelors')
        | (data['education'] == 'Prof-school')
        | (data['education'] == 'Assoc-acdm')
        | (data['education'] == 'Assoc-voc')
        | (data['education'] == 'Masters')
        | (data['education'] == 'Doctorate'))]

data7 = (data[data['salary'] == '>50K'])

len(data7) - len(data5)

3306

**7. Display age statistics for each race (*race* feature) and each gender (*sex* feature). Use *groupby()* and *describe()*. Find the maximum age of men of *Amer-Indian-Eskimo* race.**

In [14]:
data3 = data.groupby(['race'])['age'].describe()
data3

,count,mean,std,min,25%,50%,75%,max
race,,,,,,,,
Amer-Indian-Eskimo,311.0,37.173633,12.447130,17.0,28.0,35.0,45.5,82.0
Asian-Pac-Islander,1039.0,37.746872,12.825133,17.0,28.0,36.0,45.0,90.0
Black,3124.0,37.767926,12.759290,17.0,28.0,36.0,46.0,90.0
Other,271.0,33.457565,11.538865,17.0,25.0,31.0,41.0,77.0
White,27816.0,38.769881,13.782306,17.0,28.0,37.0,48.0,90.0

**8. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men (*marital-status* feature)? Consider as married those who have a *marital-status* starting with *Married* (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.**

In [15]:
data5 = data[(data['salary'] == '>50K')
        & ((data['marital-status'] == 'Married-civ-spouse')
        | (data['marital-status'] == 'Married-spouse-absent')
        | (data['marital-status'] == 'Married-AF-spouse'))]

data7 = (data[data['salary'] == '>50K'])

len(data7) - len(data5)

1105

**9. What is the maximum number of hours a person works per week (*hours-per-week* feature)? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?**

In [16]:
data7 = data['hours-per-week'].max()

In [17]:
data8 = data[data['hours-per-week'] == data['hours-per-week'].max()]
len(data8)

85

In [18]:
data9 = data[(data['salary'] == '>50K')
        & (data['hours-per-week'] == data['hours-per-week'].max())]
len(data9) * 100 / len(data8)

29.41176470588235

**10. Count the average time of work (*hours-per-week*) for those who earn a little and a lot (*salary*) for each country (*native-country*). What will these be for Japan?**

In [19]:
data10 = data[(data['salary'] == '>50K') & (data['native-country'] == 'Japan')]
data10['hours-per-week'].mean()

47.958333333333336

In [20]:
data11 = data[(data['salary'] == '<=50K') & (data['native-country'] == 'Japan')]
data11['hours-per-week'].mean()

41.0